version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk8
  build:
    commands:
      - java -version
      - gradle build
artifacts:
  files:
    - build/libs/test_project-0.1.0.jar
    - appspec.yml
  discard-paths: yes
