---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: test-project
  namespace: test-project
spec:
  replicas: 2
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: test-project
          image: 423073966355.dkr.ecr.eu-west-1.amazonaws.com/test-repository:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080